version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.13
    environment:
      TERM: dumb
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: install dependencies
          command: |
            curl -1sLf 'https://packages.circleci.com/public/setup.deb.sh' | sudo -E bash
            sudo apt install circleci
            uv tool install prek
      - run: make -C tests
workflows:
  build:
    jobs:
      - build
